/**
 * Lista de bairros da cidade de Montes Claros-MG
 */
export const bairrosMontesClaros = [
  "Alterosa",
  "Alto Boa Vista",
  "Alto São João",
  "Carmelo",
  "Centro",
  "Chiquinho Guimarães",
  "Cidade Industrial",
  "Cidade Nova",
  "Cidade Santa Maria",
  "Clarice Ataíde",
  "Dona Gregória",
  "Delfino Magalhães",
  "Dr. Edgar Pereira",
  "Dr. João Alves",
  "Dr. Olinto Alves",
  "Esplanada",
  "Ibituruna",
  "Independência",
  "JK",
  "Jaraguá",
  "João Botelho",
  "João Gordo",
  "Jardim Palmeiras",
  "Jardim Primavera",
  "Jardim São Geraldo",
  "Lourdes",
  "Major Prates",
  "Mangues",
  "Maracanã",
  "Melo",
  "Monte Carmelo",
  "Morada do Parque",
  "Morada do Sol",
  "Nossa Senhora Aparecida",
  "Nossa Senhora de Fátima",
  "Nova Morada",
  "Planalto",
  "Pão de Açúcar",
  "Renascença",
  "Sagrada Família",
  "Santa Cecília",
  "Santa Laura",
  "Santa Lúcia",
  "Santa Rita",
  "Santa Rosa",
  "Santo Antônio",
  "Santo Expedito",
  "Santos Reis",
  "São Geraldo",
  "São José",
  "São Judas",
  "São Luiz",
  "São Norberto",
  "Todos os Santos",
  "Vargem Grande",
  "Vila Anália",
  "Vila Antônio Narciso",
  "Vila Brasília",
  "Vila Greice",
  "Vila Guilhermina",
  "Vila Ipiranga",
  "Vila Luiza",
  "Vila Mauricéia",
  "Vila Oliveira",
  "Vila Raquel",
  "Vila Regina",
  "Vila Sion",
  "Vila Sumaré",
  "Vila Telma",
  "Vilage do Lago",
  "Vera Cruz"
];

/**
 * Lista de produtos comuns para sugestões de cadastro
 */
export const produtosComuns = [
  // Carnes
  { nome: "Carne Bovina - Filé Mignon (kg)", categoria: "Carnes" },
  { nome: "Carne Bovina - Contra Filé (kg)", categoria: "Carnes" },
  { nome: "Carne Bovina - Coxão Mole (kg)", categoria: "Carnes" },
  { nome: "Carne Bovina - Acém (kg)", categoria: "Carnes" },
  { nome: "Carne Bovina - Patinho (kg)", categoria: "Carnes" },
  { nome: "Carne Bovina - Maminha (kg)", categoria: "Carnes" },
  { nome: "Carne Bovina - Cupim (kg)", categoria: "Carnes" },
  { nome: "Carne Bovina - Costela (kg)", categoria: "Carnes" },
  { nome: "Carne Bovina - Picanha (kg)", categoria: "Carnes" },
  { nome: "Carne Suína - Pernil (kg)", categoria: "Carnes" },
  { nome: "Carne Suína - Costela (kg)", categoria: "Carnes" },
  { nome: "Carne Suína - Lombo (kg)", categoria: "Carnes" },
  { nome: "Frango - Peito (kg)", categoria: "Carnes" },
  { nome: "Frango - Coxa e Sobrecoxa (kg)", categoria: "Carnes" },
  { nome: "Frango - Inteiro (kg)", categoria: "Carnes" },
  { nome: "Frango - Filé de Peito (kg)", categoria: "Carnes" },
  
  // Hortifruti
  { nome: "Tomate (kg)", categoria: "Hortifruti" },
  { nome: "Batata (kg)", categoria: "Hortifruti" },
  { nome: "Cebola (kg)", categoria: "Hortifruti" },
  { nome: "Cenoura (kg)", categoria: "Hortifruti" },
  { nome: "Alho (kg)", categoria: "Hortifruti" },
  { nome: "Banana Prata (kg)", categoria: "Hortifruti" },
  { nome: "Maçã (kg)", categoria: "Hortifruti" },
  { nome: "Laranja (kg)", categoria: "Hortifruti" },
  
  // Alimentos Básicos
  { nome: "Arroz Tipo 1 - 5kg", categoria: "Alimentos" },
  { nome: "Feijão Carioca - 1kg", categoria: "Alimentos" },
  { nome: "Açúcar Cristal - 5kg", categoria: "Alimentos" },
  { nome: "Café em Pó - 500g", categoria: "Alimentos" },
  { nome: "Leite UHT Integral - 1L", categoria: "Alimentos" },
  { nome: "Óleo de Soja - 900ml", categoria: "Alimentos" },
  { nome: "Farinha de Trigo - 1kg", categoria: "Alimentos" },
  { nome: "Macarrão Espaguete - 500g", categoria: "Alimentos" },
  { nome: "Pão Francês (kg)", categoria: "Alimentos" },
  
  // Higiene e Limpeza
  { nome: "Papel Higiênico - 4 rolos", categoria: "Higiene" },
  { nome: "Sabonete - 90g", categoria: "Higiene" },
  { nome: "Creme Dental - 90g", categoria: "Higiene" },
  { nome: "Sabão em Pó - 1kg", categoria: "Limpeza" },
  { nome: "Detergente Líquido - 500ml", categoria: "Limpeza" },
  { nome: "Água Sanitária - 1L", categoria: "Limpeza" },
  
  // Bebidas
  { nome: "Refrigerante Cola - 2L", categoria: "Bebidas" },
  { nome: "Refrigerante Guaraná - 2L", categoria: "Bebidas" },
  { nome: "Cerveja Lata - 350ml", categoria: "Bebidas" },
  { nome: "Água Mineral - 1,5L", categoria: "Bebidas" },
  
  // Combustíveis
  { nome: "Gasolina Comum (litro)", categoria: "Combustível" },
  { nome: "Gasolina Aditivada (litro)", categoria: "Combustível" },
  { nome: "Etanol (litro)", categoria: "Combustível" },
  { nome: "Diesel S10 (litro)", categoria: "Combustível" },
  { nome: "Gás de Cozinha - 13kg", categoria: "Combustível" }
];